---

server:
  port: 9003
security:
  oauth2:
    resource:
      user-info-uri: ${oauth.client.user.info.uri}
spring:
  application:
    name: amisoft-secure-resource
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}


